apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vault-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vault-lera-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vault-shared-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
